apiVersion: deploy.cloud.google.com/v1
kind: DeliveryPipeline
metadata:
  name: gke-cicd-pipeline
  labels:
    app: ci-cd
description: cicd delivery pipeline
serialPipeline:
  stages:
  - targetId: dev
    # profiles:
    # - dev
  # - targetId: staging
  #   profiles:
  #   - staging
  - targetId: prod
  #   profiles:
  #   - prod
---
apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: dev
  annotations: {}
  labels: {}
description: dev
gke:
  cluster: projects/vpc-satyajith/locations/us-central1/clusters/cluster-1
--- 
apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: prod
  annotations: {}
  labels: {}
description: prod
requireApproval: true
gke:
  cluster: projects/vpc-satyajith/locations/us-central1/clusters/cluster-2
