apiVersion: deploy.cloud.google.com/v1
kind: DeliveryPipeline
metadata:
  name: gke-cicd-pipeline
  labels:
    app: ci-cd
description: cicd delivery pipeline
serialPipeline:
  stages:
  - targetId: dev
    profiles: []
  - targetId: prod # <<-- New stage for prod
    profiles: []
    # Add this block to require a manual approval
    strategy:
      standard:
        postdeploy:
          actions: []
        predeploy:
          actions: []

---
apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: dev
  annotations: {}
  labels: {}
description: dev
gke:
  cluster: projects/vpc-satyajith/locations/us-central1-a/clusters/gke-cluster-01
--- 
apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: prod
  annotations: {}
  labels: {}
description: prod
requireApproval: true
gke:
  cluster: projects/vpc-satyajith/locations/us-central1-a/clusters/gke-cluster-02